package miniJava.SyntacticAnalyzer;

/**
 *   TokenKind is a simple enumeration of the different kinds of tokens
 *   
 */

public enum TokenKind {ID, NUM, CLASS_KW, BINOP, UNOP, SUBTRACT, 
	PUBLIC_KW, PRIVATE_KW, STATIC_KW, VOID_KW, 
	RETURN_KW, THIS_KW, LBRACE, RBRACE, EXPRESSION,
	LBRACKET, RBRACKET, LPAREN, RPAREN,
	BLOCK_COMMENT_OPEN, BLOCK_COMMENT_CLOSE, TRUE_KW, FALSE_KW, 
	BOOLEAN_KW, LINE_COMMENT, SEMICOLON, NEW_KW, IF_KW, ELSE_KW, 
	WHILE_KW, EQUALS, PERIOD, COMMA, INT_KW, EOL, EOT, WHITESPACE, 
	NULL, ERROR}

